apiVersion: v1
kind: Service
metadata:
  name: otbr
  namespace: otbr
spec:
  selector:
    app: otbr
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
  - name: web
    port: 8086
    targetPort: 8086
