apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: huntarr
  namespace: huntarr
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - huntarr.sync.lt
    secretName: huntarr-letsencrypt
  rules:
  - host: huntarr.sync.lt
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: huntarr
            port:
              name: app
