apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  namespace: matter-server
  labels:
    app: matter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: ubuntu-k8s
      containers:
      - name: matter-server
        image: ghcr.io/home-assistant-libs/python-matter-server:stable
        securityContext:
          privileged: true
        args:
        - --storage-path=/data
        - --paa-root-cert-dir=/data/credentials
        ports:
        - containerPort: 5580
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: matter-server-data
