apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./ingress.yaml
- ./service.yaml
- ./configmap.yaml
- ./pvc.yaml

images:
- name: lscr.io/linuxserver/radarr
  newTag: 5.27.0-develop
